class Channel:
    """
    self.chan_id
    self.active
    self.channel_point
    self.local_node_id
    self.remote_node_id
    self.capacity
    self.commit_fee
    self.local_balance
    self.remote_balance
    self.local_base_fee
    self.local_fee_rate
    self.remote_base_fee
    self.remote_fee_rate
    self.local_alias
    self.remote_alias
    self.uptime
    self.lifetime
    self.last_forward
    self.earned_fees
    """
